spring.application.name=taskManagement
spring.datasource.url=jdbc:mysql://localhost:3306/taskManager
spring.datasource.username=vaibhaovk
spring.datasource.password=vaibhao

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

cors.allowed-origins =http://localhost:5173
debug=true

jwt.secret=88ad64755b7a4307b02d5a8e6bbb327dfbed97e10549611d3adb21738ae99973